### ISSUE TITLE
Adding onChangeText seems to break the internal text state management

### ISSUE THREAD

**Issue by Strayer** [n4kz/react-native-material-textfield#8]
I tried switching to this component from standard TextInputs and noticed that the text field content disappears on re-render when the outer components state changes in onChangeText.

I *think* this happens because onChangeText is called before changing the internal state, though I'm not sure.

https://github.com/n4kz/react-native-material-textfield/blob/master/src/components/field/index.js#L176

Its not that big of a deal as long as you set the value property on the TextField, but its not behaving like the default TextInput, since that one doesn't loose its internal state when adding a onChangeText handler.

```javascript
// TextField will loose the current value on each onChangeText
<TextField
    onChangeText={(example) => {this.setState({example: example})}}
    />

// TextField will still show the current value on each onChangeText
<TextField
    value={this.state.example}
    onChangeText={(example) => {this.setState({example: example})}}
    />
```

**Comment by Strayer** [comment]
Another (Android-only) issue of using value on the TextInput is that it kinda breaks the visuals of secureTextEntry: https://github.com/facebook/react-native/issues/11631

Not really part of this issue, but if the internal state management of TextField were to change, this should be taken into account as well. As far as I can see the original TextInput class doesn't use state to store the text, but I'm not completely sure that I understand the code: https://github.com/facebook/react-native/blob/a6df7a6c/Libraries/Components/TextInput/TextInput.js#L774-L795

**Comment by n4kz** [comment]
Thanks for reporting! When `value` prop is `undefined` `componentWillReceiveProps` method resets internal state. Fixed in bdade13 and released in 0.2.7.

**Comment by dotballV** [comment]
> Thanks for reporting! When `value` prop is `undefined` `componentWillReceiveProps` method resets internal state on every prop change. Fixed in [bdade13](https://github.com/n4kz/react-native-material-textfield/commit/bdade13a39ff669629cb7db55506941715eb1f4e) and released in 0.2.7.

This issue still there. please update as soon as possible. Thanks in advance.
